export const SET_INVOICE_DATA = "SET_INVOICE_DATA";

export const setInvoiceData = () => {
  const mergedMileStoneData = [
    {
      PROJECTID: "INV01",
      PROJECTNAME: "LexGo",
      PRODUCTS: "Zoho Desk",
      COMPLETIONSTATUS: "95%",
      PROJECTSTATUS: "On hold",
      CREATORID: "Shajin",
      CONTACTEMAIL: "shajin@elitetechpark.info",
      CONTACTPHONE: "+91 8732159846",
      Invoice_Date: "10-04-2025",
      DISCRIPTION: "you projects is on hold due to some issues",
    },
    {
      PROJECTID: "INV02",
      PROJECTNAME: "LexGo",
      PRODUCTS: "Zoho Projects",
      COMPLETIONSTATUS: "5%",
      PROJECTSTATUS: "Unpaid",
      CREATORID: "Mahindha",
      CONTACTEMAIL: "mc@elitetechpark.info",
      CONTACTPHONE: "+91 8732159846",
      Invoice_Date: "26-04-2025",
    },
    {
      PROJECTID: "INV03",
      PROJECTNAME: "LexGo",
      PRODUCTS: "Zoho Catalyst",
      COMPLETIONSTATUS: "100%",
      PROJECTSTATUS: "Paid",
      CREATORID: "Sownthariya",
      CONTACTEMAIL: "sw@elitetechpark.info",
      CONTACTPHONE: "+91 9952475661",
      Invoice_Date: "21-04-2025",
    },
    {
      PROJECTID: "INV05",
      PROJECTNAME: "LexGo",
      PRODUCTS: "Zoho CRM",
      COMPLETIONSTATUS: "0%",
      PROJECTSTATUS: "Sent",
      CREATORID: "Sownthariya",
      CONTACTEMAIL: "sw@elitetechpark.info",
      CONTACTPHONE: "+91 9952475661",
      Invoice_Date: "24-04-2025",
    },
    {
      PROJECTID: "INV08",
      PROJECTNAME: "LexGo",
      PRODUCTS: "Zoho Catalyst",
      COMPLETIONSTATUS: "50%",
      PROJECTSTATUS: "On hold",
      CREATORID: "Ramesh",
      CONTACTEMAIL: "ramesh@elitetechpark.info",
      CONTACTPHONE: "+91 8925924783",
      Invoice_Date: "25-04-2025",
      DISCRIPTION: "you projects is on hold due to some issues",
    },
    {
      PROJECTID: "INV06",
      PROJECTNAME: "LexGo",
      PRODUCTS: "Zoho Catalyst",
      COMPLETIONSTATUS: "5%",
      PROJECTSTATUS: "Draft",
      CREATORID: "Ramesh",
      CONTACTEMAIL: "ramesh@elitetechpark.info",
      CONTACTPHONE: "+91 8925924783",
      Invoice_Date: "12-04-2025",
    },
    {
      PROJECTID: "INV07",
      PROJECTNAME: "LexGo",
      PRODUCTS: "Zoho Books",
      COMPLETIONSTATUS: "35%",
      PROJECTSTATUS: "Void",
      CREATORID: "Shajin",
      CONTACTEMAIL: "shajin@elitetechpark.info",
      CONTACTPHONE: "+91 8925924783",
      Invoice_Date: "19-04-2025",
    },
    {
      PROJECTID: "INV08",
      PROJECTNAME: "LexGo",
      PRODUCTS: "Zoho Catalyst",
      COMPLETIONSTATUS: "50%",
      PROJECTSTATUS: "Partially Paid",
      CREATORID: "Ramesh",
      CONTACTEMAIL: "ramesh@elitetechpark.info",
      CONTACTPHONE: "+91 8925924783",
      Invoice_Date: "25-04-2025",
    },
    {
      PROJECTID: "INV08",
      PROJECTNAME: "LexGo",
      PRODUCTS: "Zoho Catalyst",
      COMPLETIONSTATUS: "50%",
      PROJECTSTATUS: "On hold",
      CREATORID: "Ramesh",
      CONTACTEMAIL: "ramesh@elitetechpark.info",
      CONTACTPHONE: "+91 8925924783",
      Invoice_Date: "25-04-2025",
      DISCRIPTION: "you projects is on hold due to some issues",
    },
    {
      PROJECTID: "INV09",
      PROJECTNAME: "LexGo",
      PRODUCTS: "Zoho Catalyst",
      COMPLETIONSTATUS: "50%",
      PROJECTSTATUS: "Partially Paid",
      CREATORID: "Ramesh",
      CONTACTEMAIL: "ramesh@elitetechpark.info",
      CONTACTPHONE: "+91 8925924783",
      Invoice_Date: "25-04-2025",
    },
    {
      PROJECTID: "INV10",
      PROJECTNAME: "LexGo",
      PRODUCTS: "Zoho Catalyst",
      COMPLETIONSTATUS: "50%",
      PROJECTSTATUS: "Partially Paid",
      CREATORID: "Ramesh",
      CONTACTEMAIL: "ramesh@elitetechpark.info",
      CONTACTPHONE: "+91 8925924783",
      Invoice_Date: "25-04-2025",
    },
    // Add the rest as needed
  ];

  return {
    type: SET_INVOICE_DATA,
    payload: mergedMileStoneData,
  };
};
